# Generated by Django 3.1.2 on 2020-10-31 09:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('profilePic', models.ImageField(upload_to='images/profilepics/')),
                ('name', models.CharField(max_length=100)),
                ('penName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('coverPhoto', models.ImageField(upload_to='images/singles/')),
                ('songFile', models.FileField(upload_to='songs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='home.author')),
                ('collabs', models.ManyToManyField(blank=True, related_name='collabs', to='home.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('coverPhoto', models.ImageField(upload_to='images/albums/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.author')),
                ('songs', models.ManyToManyField(to='home.Single')),
            ],
        ),
    ]
